# Generated by Django 4.2.2 on 2023-06-29 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En progreso'), ('completada', 'Completada')], max_length=15)),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_app.label', verbose_name='etiqueta')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
