# Generated by Django 4.2.2 on 2023-06-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
