# Generated by Django 4.2.2 on 2023-06-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_label_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='label_id',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
